### ISSUE TITLE
Roadmap (kinda to-do list)

### ISSUE THREAD

**Issue by lifeart** [lifeart/els-addon-typed-templates#23]
- [ ] Land this addon as class-based API, instead of function-based
- [ ] Add hover information support
- [ ] Add caching for unchanged files (use watcher API)
- [ ] Implement strategy for class/function API detection 
- [ ] Generate additional class for class based Helpers
- [ ] Generate additional class for class based Modifiers
- [ ] Generate additional class for template-less components
- [ ] Use babel templates instead of building class from plain string
- [ ] Figure out simple ways to debug current state (whrite all project into temp folder, including virtual classes?)

**Comment by emattias** [comment]
Nice stuff! The main thing stopping us from starting to use this is that we cant type all of our components and templates at once.

The main idea I can come up with to handle this is to be able to make it only add suggestions and add errors/warnings when there are types in the component that is invoked with incorrect args. 

Right now when we enable typed templates we get tons of errors in all our 900+ hbs files.

**Comment by lifeart** [comment]
@emattias fast case - using patch-package, or hands - add explict return from this function https://github.com/lifeart/els-addon-typed-templates/blob/master/dist/src/index.js#L28
like
```js
lintFile() {
   return [];
}
```
and It will disable linting issues,

in long term, I was trying to figure out how to add support for addons configuration

**Comment by lifeart** [comment]
@emattias if you need programmatic solution, you can create your own addon, set it's initialization order after `els-addon-typed-templates`, and remove linter created by addon using

`package.json`
```json
{
 "ember-language-server": {
    "entry": "./index"
  },
  "ember-addon": {
    "after": "els-addon-typed-templates"
  }
}
```


```js
/// index.js
module.exports = {
   onInit((server,project)=>{
      project.linters.pop();
   });
}
```
